### PR TITLE
Refactor stuff

### PR DESCRIPTION
**Pull request by eugene-eeo**
Added a `PyGrabbit.select` function that is basically the lifesaver for the compliance to DRY and KISS principles for the library. Instead of huge conditionals, the code is now very sequential:

``` python
result = self.select(
    XPATH1,
    XPATH2,
    XPATH3,
   ...
)
```

Also removed the `PyGrabbit.url` function, since that doesn't do anything at the moment. BTW, `url` should be contained in a `@classmethod`, not a `@staticmethod` so that subclasses will not get a PyGrabbit class when the "constructor" is called.

The previously global `headers` variable/mapping is now included in the `PyGrabbit` class, i.e. `PyGrabbit.headers` so that subclasses can for example change existing/add new headers.

### CODE REVIEW

**Comment by eugene-eeo** [comment]
@eka I can't seem to get one of the tests passing. The command I used is just `py.test tests`.

```
self = <tests.test_pygrabbit.TestPyGrabbitImages object at 0x103955400>

    @vcr.use_cassette('fixtures/vcr_cassettes/pygrabbit.yaml', record_mode='new_episodes')
    def test_return_images_from_twitter_card(self):
        g = PyGrabbit("http://momwitha.com/2013/08/having-fun-with-pictures-at-google-headquarters/")
>       assert g.images[0] == "http://momwitha.com/wp-content/uploads/2013/08/Rita-in-Google-Phonebooth1.jpg"
E       assert 'http://momwi...obby-Sign.jpg' == 'http://momwit...onebooth1.jpg'
E         - http://momwitha.com/wp-content/uploads/2013/08/Google-Lobby-Sign.jpg
E         ?                                                       ^  ^^^^^^^
E         + http://momwitha.com/wp-content/uploads/2013/08/Rita-in-Google-Phonebooth1.jpg
E         ?                                                ++++++++       ^^ ++ ^^^^^

tests/test_pygrabbit.py:56: AssertionError
```

I am sorry if I didn't run the test correctly, I don't usually use `pyvcr` but `betamax` as I _personally_ find the API more intuitive.

**Comment by estebanfeldman** [comment]
@eugene-eeo Hi, just looking over your changes.

First, thanks. Second, I cloned your repo and 5 tests failed as is. 
`5 failed, 5 passed in 0.75 seconds`
I will accept most of your changes, they look good.

But let me know when you are finished with it so I can take a deep look at it.

Thanks!

**Comment by eugene-eeo** [comment]
**I'm finished with the changes.** I think the tests are too fragile at the moment. Strangely, for me

`1 failed, 9 passed in 0.66 seconds`

From my understanding (and that's why the tests run so slowly the first time round) the vcr module downloads content from the internet the first time I run the tests? Logically speaking none of the tests should fail because I merely refactored repeated patterns into separate methods but I might've missed out on a bit. The demo works, though.

**Comment by estebanfeldman** [comment]
Merged with minimal refactor. Thanks a lot!

**Comment by eugene-eeo** [comment]
Hi, I've looked over your changes and I think that the `PyGrabbit.url` constructor should be renamed to `PyGrabbit.from_url` as it is more intuitive. Also consider passing the parsed ElementTree and the URL to the `PyGrabbit.__init__` method when initialising using `from_url`. This allows for easier testing as well as flexibility.

**Pull request merged**
